apiVersion: apps/v1
kind: Deployment
metadata:
  name: crp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crp
  template:
    metadata:
      labels:
        app: crp
    spec:
      containers:
        - name: crp
          image: ericratz.azurecr.io/crp:latest
          ports:
            - containerPort: 8000