adminPassword: admin

service:
  type: ClusterIP

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-server.default.svc.cluster.local:80
        isDefault: true

      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki.default.svc.cluster.local:3100
        isDefault: false
        jsonData:
          maxLines: 1000
          httpMethod: POST

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    searchNamespace: ALL
    folder: /var/lib/grafana/dashboards