name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #login to azure
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #login docker to acr
      - name: Login to ACR
        run: az acr login --name ericratz

      #build docker image
      - name: Build Docker image
        run: |
          docker build -t ericratz.azurecr.io/crp:latest .

      #push image to acr
      - name: Push Docker image
        run: |
          docker push ericratz.azurecr.io/crp:latest

      #connect kubectl to aks
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: cloud-reliability-rg
          cluster-name: cloud-reliability-aks

      #apply kubernetes manifests
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      #update kubernetes deployment image
      - name: Update deployment image
        run: |
          kubectl set image deployment/crp \
            crp=ericratz.azurecr.io/crp:latest

      #wait for deployment rollout
      - name: Verify rollout
        run: |
          kubectl rollout status deployment/crp

      #install k6
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -L | tar xvz
          sudo mv k6-v0.49.0-linux-amd64/k6 /usr/local/bin/k6

      #run k6 reliability check
      - name: Run k6 reliability check
        run: |
          EXTERNAL_IP=$(kubectl get svc crp -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          k6 run k6/load-test.js -e BASE_URL=http://$EXTERNAL_IP